### ISSUE TITLE
Is it possible to build standard reactjs apps with this kind of setup?

### ISSUE THREAD

**Issue by pandajump1** [jreznot/electron-java-app#12]
Is it possible to not use vaadin framework and instead use this as a template to build ui with other commonly used libraries like reactjs?

What I mean is, it would look like:
Frontend (ReactJS - Electron Based)
Backend - Java Based

**Comment by jreznot** [comment]
Hi, 
Yes you can use it for apps with any front-end technology. Just replace AppServlet with your favorite servlet, for instance with Spring boot dispatcher.
