### ISSUE TITLE
Where to set encoding to UTF-8 for Upload Field.

### ISSUE THREAD

**Issue by rpadur** [jreznot/electron-java-app#14]
Hi,

I tried to extend the demo application with an Upload-Component from Vaadin. All went fine, but the encoding of the files seems to be fixed. I want to upload files which also contain german "Umlaute" like "ä, ü, ö", but because of the wrong encoding, it didn't work.

Changing the encoding directly at the Receiver, as suggested in Stackoverflow, did not work.
Because there is no index.html, I also can't set the encoding there.

So where is the best point to change the encoding for the standalone app?
Kind regards
Ronald

**Comment by jreznot** [comment]
Sorry, I cannot help you with Vaadin. Probably, Vaadin community can help you: http://vaadin.com/forum/
