### ISSUE TITLE
Development in the IDE

### ISSUE THREAD

**Issue by afedulov** [jreznot/electron-java-app#28]
It would be great to have some description in the REAME about the development process. I can see how I can start the "backend" with the `Launcher`, but cannot figure out if it is possible to start the UI separately. Is NPM used for that? Is there some Vaadin-specific build goal?

**Comment by jreznot** [comment]
This is extremely wild example for enthusiasts only. It is not recommended for real-life applications.
Please use JCEF or Java FX embeeded web browser instead.

**Comment by afedulov** [comment]
OK, but I am interested to experiment with it and you are somehow assuming my goals. I would appreciate an answer if this is possible at all or not.

**Comment by jreznot** [comment]
It is enough to run `npm install` once and then start Launcher class from IntelliJ IDEA with Gradle integration enabled.

![image](https://user-images.githubusercontent.com/1066152/80868024-8c9d5a80-8ca0-11ea-8efc-88d60e5aaea2.png)

**Comment by afedulov** [comment]
Thanks for the quick reply, Yuriy! Despite being a very niche "wild example for enthusiasts", the project setup demonstrating bundling Java backend into an electron app is very useful. Thanks for that!
