### ISSUE TITLE
Please help me. I can't run the application. Gradle runApp

### ISSUE THREAD

**Issue by dronald-dev** [jreznot/electron-java-app#38]
Console output:

0:08:43: Executing task 'runApp'...

Starting Gradle Daemon...
Gradle Daemon started in 3 s 361 ms
> Task :compileJava UP-TO-DATE
> Task :vaadinPrepareFrontend
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :installDist UP-TO-DATE
> Task :buildApp

> Task :runApp

Server PID: 10104
Server error: The input line is too long.
The syntax of the command is incorrect.
255
Server stopped unexpectedly with code 255
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...
Waiting for the server start...

Error window:
![electron_XmUYBzev70](https://user-images.githubusercontent.com/26672809/99158030-00e89a00-26d7-11eb-8712-02e921c8986d.png)

**Comment by jreznot** [comment]
Sorry, this is extremely unstable project that should not be used if you cannot run it.
