### ISSUE TITLE
How to ensure that WebSocket is not accessed illegally?

### ISSUE THREAD

**Issue by konding** [jreznot/electron-java-app#9]
Hi,This is my question.

**Comment by jreznot** [comment]
Server app should listen only 127.0.0.1 to prevent external access, you should tune it in Jetty runner.

**Comment by konding** [comment]
Thank you for your reply.
Sure,Listen on 127.0.0.1 can prevent external access.
How do It prevent other program access in local?

**Comment by jreznot** [comment]
Integrate authentication to your application, something like login form - it is required if your application stores sensitive data. Plus you can modify UserAgent of electron part, for instance include there a secret key, then check this secret key using HTTP filter in the  server part, that will prevent random access from third party applications.

**Comment by konding** [comment]
thanks.
now i have a clue.
